### ISSUE TITLE
能不能出一个连接外部 MySQL和Redis的compose

### ISSUE THREAD

**Issue by AlanWang2333** [dromara/orion-visor#66]
我用的1panel面板，我已经有这俩数据库了，所以不想再重复安装这些数据库
然后我改了一下compose,部署之后容器显示不健康，用admin，admin登录不上去，密码是admin吗

```

version: "3.3"
services:
  orion-visor:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-visor-service:2.1.8
    container_name: orion-visor
    environment:
      - DATABASE_URL=mysql://orion:orionorion@mariadb:3306/orion?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
      # 定义数据库和缓存服务的连接参数
      - MYSQL_HOST=192.168.1.20 # MySQL主机地址，默认值为mysql
      - MYSQL_PORT=3306 # MySQL端口，默认为3306
      - MYSQL_DATABASE=orion # 使用的数据库名称，默认为orion_visor
      - MYSQL_USER=orion # MySQL用户名，默认root
      - MYSQL_PASSWORD=orionorion # MySQL密码
      - REDIS_HOST=redis # Redis主机地址，默认值为redis
      - REDIS_PASSWORD=123456666 # Redis密码
      - SECRET_KEY=12345666 # 安全密钥，用于加密操作
      - DEMO_MODE=false # 演示模式，可选
    volumes:
      - /vol1/1000/docker/test-orion-visor:/root/orion # 持久化数据挂载
    privileged: true # 赋予容器管理权限（适用于需要更高权限的应用）
    ports:
      - 1081:80
      
    healthcheck:
      # 健康检查设置
      test:
        - CMD
        - curl
        - http://127.0.0.1:9200/orion-visor/api/server/bootstrap/health
#数组形式来定义命令      test: ["CMD", "curl", "http://127.0.0.1:9200/orion-visor/api/server/bootstrap/health"]
        
        # 检查API健康状态
      interval: 15s # 每15秒进行一次检查
      timeout: 300s # 超时时间为300秒
      retries: 15 # 尝试次数为15次
      start_period: 3s # 启动后等待3秒再开始健康检查
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true

```
