### ISSUE TITLE
有ARM版吗？up -d以后无法用

### ISSUE THREAD

**Issue by chenryace** [dromara/orion-visor#69]

**Comment by lijiahangmax** [comment]
暂时没有  我的服务器不是arm架构的, 所以我没办法提供, 你可以自行构建docker 镜像, /docker 中有 Dockerfile

**Comment by lijiahangmax** [comment]
你可以修改后提个pr或者把docker发我, 我提交一下

**Comment by whatevertuzi** [comment]
> 暂时没有 我的服务器不是arm架构的, 所以我没办法提供, 你可以自行构建docker 镜像, /docker 中有 Dockerfile

可以用docker buildx ，打多平台的tar包

**Comment by whatevertuzi** [comment]
> > 暂时没有 我的服务器不是arm架构的, 所以我没办法提供, 你可以自行构建docker 镜像, /docker 中有 Dockerfile
> 
> 可以用docker buildx ，打多平台的tar包

https://www.voidking.com/dev-docker-buildx/   供参考😊

**Comment by yanhao98** [comment]
临时做了一个，后面考虑整理下，PR过来。

https://github.com/yanhao98/orion-visor/tree/feat-docker-multiarch

ARM 启动回放
[![asciicast](https://asciinema.org/a/704628.svg)](https://asciinema.org/a/704628)

## docker-compose.yml
```yaml
volumes:
  redis:
  mysql:
services:
  ui:
    image: ghcr.io/yanhao98/orion-visor-ui:feat-docker-multiarch
    build:
      context: .
      dockerfile: docker-multiarch/Dockerfile.ui
    ports:
      - 1081:80
    depends_on:
      - service
  service:
    image: ghcr.io/yanhao98/orion-visor-service:feat-docker-multiarch
    build:
      context: .
      dockerfile: docker-multiarch/Dockerfile.service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: orion_database
      MYSQL_USER: orion_mysql_user
      MYSQL_PASSWORD: orion_mysql_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      SECRET_KEY: secret_key_s12aTc89Hpjvr64J
      DEMO_MODE: false
  mysql:
    image: ghcr.io/yanhao98/orion-visor-mysql:feat-docker-multiarch
    build:
      context: .
      dockerfile: docker-multiarch/Dockerfile.mysql
    environment:
      MYSQL_DATABASE: orion_database
      MYSQL_USER: orion_mysql_user
      MYSQL_PASSWORD: orion_mysql_pass
      MYSQL_ROOT_PASSWORD: orion_mysql_root_pass
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:7-alpine
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis:/data
    command: redis-server --requirepass 'redis_pass'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 1s
      start_interval: 1s
```
